pub mod scanner;
pub mod parser;
pub mod analyzer;
pub mod resolver;

use std::fmt;
use std::error::Error;
use std::path::{Path, PathBuf};
use std::time::Instant;
use std::collections::HashMap;
use rayon::prelude::*;
use crate::ir::ClassIR;
use crate::registry::TypeRegistry;
use crate::writer::{self, WriteResult};
use crate::config::BuildConfig;
use crate::plugin::PluginRegistry;
use dashmap::DashMap;

/// Result of a build run.
pub struct BuildResult {
    pub files_generated: usize,
    pub files_skipped: usize,
    pub files_failed: usize,
    pub duration_ms: u128,
    pub errors: Vec<(PathBuf, String)>,
    pub generated_content: Vec<(PathBuf, String)>,
}

/// Errors that can occur in the pipeline.
#[derive(Debug)]
pub enum PipelineError {
    Scanner(scanner::ScanError),
}

impl fmt::Display for PipelineError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PipelineError::Scanner(e) => write!(f, "Scanner error: {}", e),
        }
    }
}

impl Error for PipelineError {}

/// Runs the full build pipeline.
pub fn run(
    root: &Path,
    config: &BuildConfig,
    plugin_registry: &PluginRegistry,
    _verbose: bool,
    cache: &DashMap<PathBuf, u64>,
) -> Result<BuildResult, PipelineError> {
    let start = Instant::now();

    // 1. Scan using configured glob patterns
    let files = scanner::scan(root, &config.include_patterns).map_err(PipelineError::Scanner)?;

    // 2. Parse files in parallel
    let parse_results: Vec<_> = files
        .into_par_iter()
        .map(|p| (p.clone(), parser::parse_file(&p)))
        .collect();

    let mut parsed_files = Vec::new();
    let mut errors = Vec::new();

    for (path, res) in parse_results {
        match res {
            Ok(p) => parsed_files.push(p),
            Err(e) => errors.push((path, e.to_string())),
        }
    }

    // 3. Analyze parsed files in parallel
    let analyze_results: Vec<_> = parsed_files
        .par_iter()
        .map(|p| (p, analyzer::analyze(p)))
        .collect();

    let mut ir_list = Vec::new();
    for (p, res) in analyze_results {
        match res {
            Ok(irs) => ir_list.extend(irs),
            Err(e) => errors.push((p.path.clone(), e.to_string())),
        }
    }

    if ir_list.is_empty() {
        return Ok(BuildResult {
            files_generated: 0,
            files_skipped: 0,
            files_failed: errors.len(),
            duration_ms: start.elapsed().as_millis(),
            errors,
            generated_content: Vec::new(),
        });
    }

    // 4. Build TypeRegistry (Pass 1)
    let type_registry = TypeRegistry::build(&ir_list, &parsed_files);

    // 5. Resolve IR in parallel (Pass 2)
    let resolved_ir: Vec<ClassIR> = ir_list
        .into_par_iter()
        .map(|ir| resolver::resolve(ir, &type_registry))
        .collect();

    // 6. Dispatch via PluginRegistry — group by source file first
    let mut grouped: HashMap<PathBuf, Vec<ClassIR>> = HashMap::new();
    for ir in resolved_ir {
        grouped.entry(ir.source_file.clone()).or_default().push(ir);
    }

    let mut generated_content = Vec::new();
    let mut files_generated = 0;
    let mut files_skipped = 0;

    for (_source, irs) in grouped {
        // Accumulate per output file: path -> (source_filename, body_content)
        // Each plugin.generate() returns a class body starting with '\n'; the pipeline
        // prepends the file header once per output file.
        let mut outputs: HashMap<PathBuf, (String, String)> = HashMap::new();

        for ir in &irs {
            let source_name = ir
                .source_file
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or("unknown.dart")
                .to_string();

            for annotation in &ir.annotations {
                let options = config.options_for(&annotation.name);
                for plugin in plugin_registry.plugins_for(&annotation.name) {
                    for file in plugin.generate(ir, &options) {
                        let out = PathBuf::from(&file.path);
                        let entry = outputs
                            .entry(out)
                            .or_insert_with(|| (source_name.clone(), String::new()));
                        // Append class body — each body starts with '\n' for proper spacing
                        entry.1.push_str(&file.content);
                    }
                }
            }
        }

        for (output_path, (file_name, body)) in outputs {
            // Combine header + all class bodies into the final file content
            let content = format!(
                "// GENERATED BY VELTRO — DO NOT EDIT\npart of '{}';{}",
                file_name, body
            );

            match writer::write_if_changed(&output_path, &content, cache) {
                WriteResult::Written => {
                    files_generated += 1;
                    generated_content.push((output_path, content));
                }
                WriteResult::Skipped => {
                    files_skipped += 1;
                }
                WriteResult::Error(e) => {
                    errors.push((output_path, e.to_string()));
                }
            }
        }
    }

    Ok(BuildResult {
        files_generated,
        files_skipped,
        files_failed: errors.len(),
        duration_ms: start.elapsed().as_millis(),
        errors,
        generated_content,
    })
}
